import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./components/views/Navbar/Index";
import Wrapper from "./components/shared/Wrapper/Index";
import Footer from "./components/views/Footer/Index";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
          <Navbar />
          <div className="min-h-screen">
          {children}
          </div>
          <Footer/>
        </Wrapper>
      </body>
    </html>
  );
}
